driver:
  enabled: true
  # repository: nvcr.io/nvidia/driver
  # choose a driver version compatible with your GPU + CUDA 12.x (example)
  # NVIDIA GPU driver - https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html#known-issue
  # https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/
  # 13.x >= 580
  # 12.x >= 525, <580
  # 11.x >= 450, <525
  #
  # Delete the cluster policy before each change
  # version: "575.57.08" # CUDA 12.9
  version: "570.195.03" # CUDA 12.8
  upgradePolicy:
    autoUpgrade: false
