configMap:
  session:
    cookies:
      - domain: 'authelia.viktorbarzin.me'
        authelia_url: 'https://authelia.viktorbarzin.me'

  storage:
    local:
      path: '/config/db.sqlite3'


  theme: light
  # Error 1: access_control (The warning)
  access_control:
    default_policy: 'one_factor' # Change to 'two_factor' once you have 2FA set up
    rules:
      - domain: "*.viktorbarzin.me"
        policy: one_factor

  # Error 2: authentication_backend (Where users are stored)
  authentication_backend:
    file:
      path: /config/users.yml
  